package KnowledgeNodeEditor;

import Models.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.AbstractListModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Gavin
 */
public class KnowledgeNodeLinkerApp extends javax.swing.JDialog { 
    
    private KnowledgeMap map;
    private KnowledgeNode node, selected;
    private boolean chosen = false; // safe lock for passing selected item
    /**
     * Creates new form KnowledgeNodeAppendApp
     */
    public KnowledgeNodeLinkerApp(KnowledgeMap map, KnowledgeNode node) {
        this.map = map;
        this.node = node;
        this.selected = null;
        initComponents();
        setModal(true);
        
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        sourceRaido = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        destinationRadio = new javax.swing.JRadioButton();
        neighborRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        selectedListString = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Knowledge Node Linker");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        DefaultComboBoxModel<String> comboBoxModel = new javax.swing.DefaultComboBoxModel<>();
        comboBoxModel.addElement("Choose a catagory");
        for (String s : map.getMap().keySet()) comboBoxModel.addElement(s);
        jComboBox1.setFont(new java.awt.Font("华文细黑", 0, 14)); // NOI18N
        jComboBox1.setModel(comboBoxModel);
        jComboBox1.setBorder(null);
        jComboBox1.setMinimumSize(new java.awt.Dimension(50, 30));
        jComboBox1.setPreferredSize(new java.awt.Dimension(50, 30));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(jComboBox1, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(256, 128));

        jList1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 255)));
        jList1.setFont(new java.awt.Font("华文细黑", 0, 14)); // NOI18N
        jList1.setModel(listModelFactory((ArrayList<KnowledgeNode>) map.getAllKnowledgeNodes())
        );
        jList1.setName(""); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 318;
        gridBagConstraints.ipady = 387;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 69, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        sourceRaido.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(sourceRaido);
        sourceRaido.setFont(new java.awt.Font("华文细黑", 1, 14)); // NOI18N
        sourceRaido.setForeground(new java.awt.Color(153, 153, 153));
        sourceRaido.setSelected(true);
        sourceRaido.setText(node.getSources().getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 24, 0, 0);
        getContentPane().add(sourceRaido, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("华文琥珀", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(265, 97, 69, 44);
        getContentPane().add(jButton1, gridBagConstraints);

        destinationRadio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(destinationRadio);
        destinationRadio.setFont(new java.awt.Font("华文细黑", 1, 14)); // NOI18N
        destinationRadio.setForeground(new java.awt.Color(153, 153, 153));
        destinationRadio.setText(node.getDestinations().getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 0);
        getContentPane().add(destinationRadio, gridBagConstraints);

        neighborRadio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(neighborRadio);
        neighborRadio.setFont(new java.awt.Font("华文细黑", 1, 14)); // NOI18N
        neighborRadio.setForeground(new java.awt.Color(153, 153, 153));
        neighborRadio.setText(node.getNeighbors().getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 0);
        getContentPane().add(neighborRadio, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("华文琥珀", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setLabelFor(jList1);
        jLabel2.setText("Avaliable Nodes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 6, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        selectedListString.setText("Add\n\n[" + "]\n\nto " + node.getName() + " as");
        selectedListString.setEditable(false);
        selectedListString.setColumns(20);
        selectedListString.setFont(new java.awt.Font("华文细黑", 0, 18)); // NOI18N
        selectedListString.setLineWrap(true);
        selectedListString.setRows(6);
        selectedListString.setToolTipText("");
        selectedListString.setWrapStyleWord(true);
        selectedListString.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 255)));
        jScrollPane3.setViewportView(selectedListString);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 24, 0, 44);
        getContentPane().add(jScrollPane3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String scope = (String) jComboBox1.getSelectedItem();
            jComboBox1.setSelectedItem(scope);
            updateListItems(scope);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void updateListItems(String scope) {
        ArrayList<KnowledgeNode> a;
        if (scope.equals("Choose a catagory"))
            a = (ArrayList<KnowledgeNode>) map.getAllKnowledgeNodes();
        else {
            a = (ArrayList<KnowledgeNode>) map.getCatagory(scope);
            Collections.sort(a, KnowledgeNodeList.comparatorBySignificance());
        }
        jList1.setModel(listModelFactory(a));
    }
    
    private AbstractListModel<KnowledgeNode> listModelFactory(final ArrayList<KnowledgeNode> accounts) {
        return new AbstractListModel<KnowledgeNode>() {
            ArrayList<KnowledgeNode> accountList = accounts;

            public int getSize() {
                return accountList.size();
            }

            public KnowledgeNode getElementAt(int i) {
                return accountList.get(i);
            }
        };
    }
    
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        selected = jList1.getSelectedValue();
        if (selected == null) return;
        selectedListString.setText("Add\n\n[" + selected.getName() + "]\n\nto " + node.getName() + " as");
        if (evt.isControlDown()) {
            String nodelist = "[";
            int listSize = jList1.getSelectedValuesList().size();
            for (int i = 0; i < listSize-1; i++) {
                KnowledgeNode k = jList1.getSelectedValuesList().get(i);
                nodelist += k.getName() + ", ";
            }
            nodelist += jList1.getSelectedValuesList().get(listSize-1).getName();

            selectedListString.setText("Add\n\n" + nodelist + "]\n\nto " + node.getName() + " as");
        } else if (evt.getClickCount() == 2) 
            KnowledgeNodeWikiApp.run(selected);
    }//GEN-LAST:event_jList1MouseClicked

    private void checkBeforeSubmit() {
        if (selected == null)
            throw new InvalidInputException("Select a node before submit");
        else if (selected == node)
            throw new InvalidInputException("Must not be a same node");
        else
            chosen = true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            checkBeforeSubmit();
            dispose();
        } catch(InvalidInputException e) {
            GeneralController.errorMessageBox(e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void run(boolean center) {
        EnhanceAppView.enhanceVision();
        if (center)
            setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public ArrayList<KnowledgeNode> getSelected() {
        ArrayList<KnowledgeNode> nodelist = (ArrayList<KnowledgeNode>) jList1.getSelectedValuesList();
        if (nodelist.isEmpty())
            return null;
        return nodelist;
    }
    
    public int getExpandedGroup() {
        if (this.sourceRaido.isSelected()) 
            return 1;
        else if (this.destinationRadio.isSelected())
            return 2;
        else
            return 3;
    }
    
    // unit test
    public static void main(String args[]) {
        KnowledgeNode a = new KnowledgeNodeImpl("A", "Character", "A", "First", "Source", "Destination", "Neighbor");
        KnowledgeNode b = new KnowledgeNodeImpl("B", "Character", "B", "Second", "Source", "Destination", "Neighbor");
        KnowledgeNode c = new KnowledgeNodeImpl("C", "String", "C", "Third", "Source", "Destination", "Neighbor");
        KnowledgeNode d = new KnowledgeNodeImpl("D", "Character", "D", "Fourth", "Source", "Destination", "Neighbor");
        KnowledgeNode e = new KnowledgeNodeImpl("E", "Character", "E", "Fourth", "Source", "Destination", "Neighbor");
        KnowledgeNode f = new KnowledgeNodeImpl("F", "Character", "F", "Fourth", "Source", "Destination", "Neighbor");

        
        KnowledgeMap map = new KnowledgeMapImpl("K");
        map.addCatagory("Character");
        map.addCatagory("String");
        map.addKnowledgeNodeTo("Character", a);
        map.addKnowledgeNodeTo("Character", b);
        map.addKnowledgeNodeTo(c.getCatagory(), c);
        map.addKnowledgeNodeTo("Character", d);
        map.addKnowledgeNodeTo("Character", e);
        
        new KnowledgeNodeLinkerApp(map, a).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton destinationRadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<Models.KnowledgeNode> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton neighborRadio;
    private javax.swing.JTextArea selectedListString;
    private javax.swing.JRadioButton sourceRaido;
    // End of variables declaration//GEN-END:variables
}
